name: calendar_range
description: Calendar multiple days selections.
version: 1.0.0
author: neil <chen2847006@gmail.com>
homepage: https://github.com/Neil2847/calendar_range

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


